name: maven cucumber run

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'app/**'
      - 'tests/features/**'
      - 'tests/runners/cucumber/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Cache .m2/repository
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles( 'inputs.project_path/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: run tests
        id: tests
        run: mvn clean test site --file tests/runners/cucumber/pom.xml

      - name: publish to git
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: cucumber results
          file_pattern: tests/results/allure/**